export const SET_CUSTOMER_DATA = "SET_CUSTOMER_DATA";
export const UPDATE_MEDICINESDP_BATCHES = "UPDATE_MEDICINESDP_BATCHES";
export const SET_APPROVED_MEDICINEDP_BATCHES =
  "SET_APPROVED_MEDICINEDP_BATCHES";
export const SET_EXPIRED_MEDICINEDP_BATCHES = "SET_EXPIRED_MEDICINEDP_BATCHES";
