export const SET_DISTRIBUTOR_DASHBOARD_DATA = "SET_DISTRIBUTOR_DASHBOARD_DATA";
export const SET_RECEIEVED_MEDICINES = "SET_RECEIEVED_MEDICINES";
export const SET_TRANSFERRED_MEDICINES = "SET_TRANSFERRED_MEDICINES";
